name: olist_agent_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pyspark==3.5.0
      - pandas==2.1.4
      - databricks-langchain==0.1.0 # Requires langchain-community>=0.2.0
      - langchain-core>=0.2.0
      - langchain-community>=0.2.0
      - kagglehub==0.2.4
      - mlflow==2.11.3
      - openai==1.14.3
      - pyarrow==15.0.0
